spring.application.name=lrms
spring.profiles.active=dev

# JPA
spring.jpa.open-in-view=false

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized